Sergey_Krivokhizha_cryptanalyzer
eTmy/cryptanalyzer pull request #1
Opened 2022-03-12 12:06 UTC by eTmy

2022-03-16 19:44 UTC, eTmy commented
Первая версия бота.  
К сожалению очень ограничен во времени, надеюсь успею доделать все задуманное, но для подстраховки пускай будет эта версия

В планах: 
* дописать недостающие проверки у команд (например если выполнить /decode, /encode /brutforce с не установленными путями, то программа свалится в исключение) 
* при использовании брутфорса перечислять расшифрованные варианты в консоль и в случае подтверждения пользователем, сохранять только правильный вариант. (Сейчас весь список вариантов просто сохраняется в файл)
* сделать возможность декодирования путем синтаксического анализа

2022-03-17 21:45 UTC, AndryLat requested changes

2022-03-17 21:45 UTC, AndryLat commented on src/main/java/com/etmy/command/BruteforceCommand.java
> +public class BruteforceCommand implements Command{
Всегда делай автоформатирование кода перед коммитом.

2022-03-17 21:45 UTC, AndryLat commented on src/main/java/com/etmy/command/BruteforceCommand.java
> +    private final SendMessageService sendMessageService;
Я в самом начале говорил о правильной организации кода. Сначала константы, потом поля класса.

2022-03-17 21:45 UTC, AndryLat commented on src/main/java/com/etmy/command/BruteforceCommand.java
> +    public static final String SUCCESS_ENCODE_MESSAGE = SendMessageServiceImpl.DELIMITER_MESSAGE + "\n"
Меня смущает, что мы ссылаемся на класс конкретной реализации. А если завтра подменят имплементацию интерфейса, что делать будем ?

2022-03-17 21:45 UTC, AndryLat commented on src/main/java/com/etmy/command/BruteforceCommand.java
> +    public static final String TRY_DECODE_MESSAGE = SendMessageServiceImpl.DELIMITER_MESSAGE + "\n"
Зачем public?

2022-03-17 21:45 UTC, AndryLat commented on src/main/java/com/etmy/command/BruteforceCommand.java
> +        String srcWriteFile = ioFileService.getWritePath();
Странные имена переменных. Почему не inputFile и outputFile? коротко и понятно, что один файл содержит входящую инфу, второй - результаты.

2022-03-17 21:45 UTC, AndryLat commented on src/main/java/com/etmy/command/BruteforceCommand.java
> +            for (int i = 0; i < 43; i++) {
Что такое 43 и почему именно 43?

2022-03-17 21:45 UTC, AndryLat commented on src/main/java/com/etmy/command/BruteforceCommand.java
> +package com.etmy.command;
com.etmy - домен компании, ок, а где пакет приложения? В компании может быть тысячи и десятки тысяч проектов.

2022-03-17 21:45 UTC, AndryLat commented on src/main/java/com/etmy/command/Command.java
> +        1) Унаследовать везде оба метода
можно бросать UnsupportedException если нет реализации метода. Чтобы другие разработчики его не использовали.

2022-03-17 21:45 UTC, AndryLat commented on src/main/java/com/etmy/command/CommandName.java
> +    public String getCommandName(){
тебя не смущает Command.getCommandName? почему не просто command.getName() ?

2022-03-17 21:45 UTC, AndryLat commented on src/main/java/com/etmy/command/DecodeCommand.java
> +    public static final String COUNT_CHARACTER_ERROR_MESSAGE = SendMessageServiceImpl.DELIMITER_MESSAGE + "\n"
DELIMITER_MESSAGE должен быть либо в comman либо где-то отдельно, сильно завязано на этот класс все.

2022-03-17 21:45 UTC, AndryLat commented on src/main/java/com/etmy/command/DecodeCommand.java
> +        if (commandArg.equals("")) {
А если commandArg придет null? Всегда надо проверять от того, что меньше всего вероятности будет null. то есть "".equals(...)

2022-03-17 21:45 UTC, AndryLat commented on src/main/java/com/etmy/command/DecodeCommand.java
> +            +"Количество сдвигаемых символов не может превышать 42 ";
Если завтра надо изменить значение этой константы, то тебе будет очень больно по всему коду бегать и искать ее значение. я про 42

2022-03-17 21:45 UTC, AndryLat commented on src/main/java/com/etmy/command/DecodeCommand.java
> +            if (countCharacters < 43) {
а особенно ты хорош в том, что где-т оты используешь 42, а где-то - 43. Если завтра ты должен будешь поменять это значение - это будет просто ад!

2022-03-17 21:45 UTC, AndryLat commented on src/main/java/com/etmy/command/DecodeCommand.java
> +                    List<String> fileLines = IO.readFileAndReturnListOfStrings(srcReadFile);
почему не назвать прост lines?

2022-03-17 21:45 UTC, AndryLat commented on src/main/java/com/etmy/command/EncodeCommand.java
> +        } else {
таких элсе, где вся логика надо избегать.  Делаем после 35 строки ретурн и все.

2022-03-17 21:45 UTC, AndryLat commented on src/main/java/com/etmy/command/EncodeCommand.java
> +            sendMessageService.sendMessage(ERROR_ARG_MESSAGE);
а саму валидацию можно вынести в отдельный метод в абстрактный класс.

2022-03-17 21:45 UTC, AndryLat commented on src/main/java/com/etmy/command/HelpCommand.java
> +    private final String HELP_MESSAGE =
это никогда не будет меняться, зачем каждый раз генерирвоать этот текст заново?

2022-03-17 21:45 UTC, AndryLat commented on src/main/java/com/etmy/command/WellcomeCommand.java
> +            Thread.sleep(1000);
5 секунд жизни впустую:) Зачем такая длительная задержка?:)

2022-03-17 21:45 UTC, AndryLat commented on src/main/java/com/etmy/cryptology/Cryptology.java
> +        for (String raw : fileLines) {
raw не совсем понятно в этом контексте

2022-03-17 21:45 UTC, AndryLat commented on src/main/java/com/etmy/io/IO.java
> +public class IO {
не нравится мне это имя.

2022-03-17 21:45 UTC, AndryLat commented on src/main/java/com/etmy/io/IO.java
> +        if (Path.of(srcFile).getParent() == null) return false;
не надо операторов в одну строку. и у ифа всегда хорошо бы иметь фигурные скобки.

2022-03-17 21:45 UTC, AndryLat commented on src/main/java/com/etmy/service/IOFileService.java
> +    void setReadPath(String readPath);
вообще непонятные имена методов, я бы не догадался, что они значат.

2022-03-17 21:45 UTC, AndryLat commented
В целом, решение очень красивое, немного затыков, но в целом круто

2022-03-23 06:51 UTC, eTmy commented on src/main/java/com/etmy/command/WellcomeCommand.java
> +            Thread.sleep(1000);
Анимация запуска приложения (:

2022-03-30 18:22 UTC, merged